"""rename department

Revision ID: 860039c7fdb9
Revises: 2036b4d19347
Create Date: 2025-05-09 14:24:26.341786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860039c7fdb9'
down_revision = '2036b4d19347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('departments', 'department')
    # ### end Alembic commands ###
